Change default MAC address to a valid SimPrints MAC address Fix friendly name generation from the MAC address UN20EX1 changes - InitScript - add possibility of starting ftp server (off by default) - replacement library for UN20EX1 - delete any existing index.tar file when installing - Return an error code from the un20 server app if it fails to startup - Modify push-files.sh to use the ftp server instead of adb - Modify Makefile to provide ftp based transfer instructions - Modify start-index-un20 script. -- Better way to pass debug parameter -- Check for error exit of App and do not shutdown if an error occurs (to avoid problem of immediate shutdown on error) -- Redirect script output to /dev/ttyS3 so we can see what is happening during startup
git-svn-id: http://svn:8000/svn/INDEX/trunk@104 71e9ff3b-2aa0-ee42-b4dd-db5a0b4f3664

diff --git a/fw/LinuxUN20/start-index-un20 b/fw/LinuxUN20/start-index-un20
--- a/fw/LinuxUN20/start-index-un20
+++ b/fw/LinuxUN20/start-index-un20
@@ -1,11 +1,15 @@
 #!/bin/sh
+{
+DEBUG_OPTION=""
 echo "Starting UN20 server application"
 if [ -e /data/un20-debug ]; then
 echo "UN20 debug enabled"
-/data/index-un20app /dev/ttyS1 debug
-else
-/data/index-un20app /dev/ttyS1
+DEBUG_OPTION="debug"
 fi
+
+/data/index-un20app /dev/ttyS1 ${DEBUG_OPTION}
+
+if [ "$?" = "0" ]; then
 # when the app exits we need to halt
 if [ -e /data/no-shutdown ]; then
 echo "Shutdown inhibited by /data/no-shutdown"
@@ -13,3 +17,8 @@ else
 echo "Requesting system to shutdown"
 /sbin/halt
 fi
+else
+echo "Application returned error NOT shutting down"
+fi
+
+} > /dev/ttyS3 2>&1
